dbt_training:
  outputs:
    dev:
      account: vn13262.north-europe.azure
      database: ANALYTICS_DEV
      password: "{{ env_var('DBT_PASSWORD') }}" # this was created as a secret in Settings within Github
      role: dbt_training
      schema: dbt_DLR
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}" # this was created as a secret in Settings within Github
      warehouse: DBT_TRAINING_WH
    prod:
      account: vn13262.north-europe.azure
      database: ANALYTICS
      password: "{{ env_var('DBT_PASSWORD') }}" # this was created as a secret in Settings within Github
      role: dbt_training
      schema: dbt_DLR
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}" # this was created as a secret in Settings within Github
      warehouse: DBT_TRAINING_WH      
  target: dev
