name: scheduled_cron_runs

on:
  schedule:
  # runs "at minute 0 of every hour"
  - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dbt
        run: pip install dbt-snowflake
        
      - name: Run dbt deps # this would not be needed if there were no packages within the model
        run: dbt deps --profiles-dir .

      - name: Run dbt build
        run: dbt build --profiles-dir .
